language: go
go:
- 1.4
before_install:
- gofmt .
install:
- export PATH=$PATH:$HOME/gopath/bin
- go get -v ./...
test:
- godep go test -v ./...
deploy:
  provider: heroku
  api_key:
    secure: PvvBdy5IgzvXDGrSo1A4iyNvBpaiRbaJfT+RbnSx71qLXIJwksYR7ygra+z3MC8RaOtdwAbl+RXZCXLcF9wWiaofr36SoHvKr4X2neW2TLzxCmyw/d0zzb6zUBJF6xddhW0PIJpZ84xeGtpto3ND3N8UnssLRm3Dxzfsuaog/Fw=
  app: nihongo-io
  on:
    repo: gojp/nihongo
  strategy: git
